; LumiGlyph - 5-bar linkage LED drawing machine
; M5StickC Plus + 2x micro servo + WS2812B

[env:m5stick-c]
platform = espressif32
board = m5stick-c
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
lib_deps =
    m5stack/M5StickCPlus @ ^0.1.0
    madhephaestus/ESP32Servo @ ^0.13.0
    fastled/FastLED @ ^3.7.0
